= Spring Boot R2DBC Starter

This experimental project provides a simple way to try the new R2DBC support through R2DBC Client and Spring Data R2DBC.


== Starters

* `spring-boot-starter-r2dbc`: Starter using R2DBC Client.
* `spring-boot-starter-data-r2dbc`: Starter using Spring Data R2DBC

== Supported Drivers

=== H2 (Embedded)

Dependencies:

[source,xml]
----
<dependency>
  <groupId>io.r2dbc</groupId>
  <artifactId>r2dbc-h2</artifactId>
</dependency>
----

Configuration embedded mode:

.application.properties
[source,xml]
----
# Nothing to do here.
----

NOTE: Spring Boot has support for embedded H2 databases using the JDBC interfacing option. Spring Boot's R2DBC configuration picks up H2 configuration details to ensure all R2DBC operations are executed on the same database instance.

Configuration in-memory:

.application.properties
[source,xml]
----
spring.r2dbc.url=r2dbc:h2:mem:///<database>?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=…
spring.r2dbc.password=…
----

Configuration file:

.application.properties
[source,xml]
----
spring.r2dbc.url=r2dbc:h2:file:///<path>/<to>/<database>?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=…
spring.r2dbc.password=…
----

=== MySQL

Dependencies (pulled from jitpack.io):

[source,xml]
----
<dependency>
  <groupId>com.github.mirromutth</groupId>
  <artifactId>r2dbc-mysql</artifactId>
</dependency>

<repository>
  <id>jitpack.io</id>
  <url>https://jitpack.io</url>
</repository>
----

Configuration:

.application.properties
[source,xml]
----
spring.r2dbc.url=r2dbc:mysql://<server>:<port>/<database>
spring.r2dbc.username=…
spring.r2dbc.password=…
----

=== PostgreSQL

Dependencies:

[source,xml]
----
<dependency>
  <groupId>io.r2dbc</groupId>
  <artifactId>r2dbc-postgresql</artifactId>
</dependency>
----

Configuration:

.application.properties
[source,xml]
----
spring.r2dbc.url=r2dbc:postgresql://<server>:<port>/<database>
spring.r2dbc.username=…
spring.r2dbc.password=…
----

=== SQL Server

Dependencies:

[source,xml]
----
<dependency>
  <groupId>io.r2dbc</groupId>
  <artifactId>r2dbc-mssql</artifactId>
</dependency>
----

Configuration:

.application.properties
[source,xml]
----
spring.r2dbc.url=r2dbc:mssql://<server>:<port>/<database>
spring.r2dbc.username=…
spring.r2dbc.password=…
----
